export const MODEL_QUALITIES = ['fast', 'standard'];

export const MODEL_PROFILES = [
  {
    id: 'chatgpt',
    label: 'ChatGPT',
    provider: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    standardModel: 'gpt-5.4',
    fastModel: 'gpt-5.4-mini',
    apiKeyEnv: ['OPENAI_API_KEY'],
    modelEnv: ['TRPG_CHATGPT_MODEL'],
    standardModelEnv: ['TRPG_CHATGPT_STANDARD_MODEL'],
    fastModelEnv: ['TRPG_CHATGPT_FAST_MODEL'],
    baseUrlEnv: ['TRPG_CHATGPT_BASE_URL'],
    supportsJson: true,
    supportsStreaming: true,
    supportsFileUpload: true,
    timeoutMs: { fast: 60000, standard: 180000 },
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    provider: 'deepseek',
    baseUrl: 'https://api.deepseek.com',
    standardModel: 'deepseek-v4-pro',
    fastModel: 'deepseek-v4-flash',
    apiKeyEnv: ['DEEPSEEK_API_KEY'],
    modelEnv: ['TRPG_DEEPSEEK_MODEL'],
    standardModelEnv: ['TRPG_DEEPSEEK_STANDARD_MODEL'],
    fastModelEnv: ['TRPG_DEEPSEEK_FAST_MODEL'],
    baseUrlEnv: ['TRPG_DEEPSEEK_BASE_URL'],
    supportsJson: true,
    supportsStreaming: true,
    supportsFileUpload: false,
    timeoutMs: { fast: 180000, standard: 420000 },
  },
  {
    id: 'gemini',
    label: 'Gemini',
    provider: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    standardModel: 'gemini-3-pro-preview',
    fastModel: 'gemini-3-flash-preview',
    apiKeyEnv: ['GEMINI_API_KEY', 'GOOGLE_API_KEY'],
    modelEnv: ['TRPG_GEMINI_MODEL'],
    standardModelEnv: ['TRPG_GEMINI_STANDARD_MODEL'],
    fastModelEnv: ['TRPG_GEMINI_FAST_MODEL'],
    baseUrlEnv: ['TRPG_GEMINI_BASE_URL'],
    supportsJson: true,
    supportsStreaming: true,
    supportsFileUpload: true,
    timeoutMs: { fast: 60000, standard: 180000 },
  },
  {
    id: 'doubao',
    label: 'Doubao',
    provider: 'doubao',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    standardModel: 'doubao-seed-2-0-pro-260215',
    fastModel: 'doubao-seed-2-0-mini-260215',
    apiKeyEnv: ['DOUBAO_API_KEY', 'TRPG_DOUBAO_API_KEY', 'ARK_API_KEY'],
    modelEnv: ['TRPG_DOUBAO_MODEL'],
    standardModelEnv: ['TRPG_DOUBAO_STANDARD_MODEL'],
    fastModelEnv: ['TRPG_DOUBAO_FAST_MODEL'],
    baseUrlEnv: ['TRPG_DOUBAO_BASE_URL'],
    supportsJson: true,
    supportsStreaming: true,
    supportsFileUpload: false,
    timeoutMs: { fast: 180000, standard: 180000 },
  },
  {
    id: 'qwen',
    label: 'Qwen',
    provider: 'qwen',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    standardModel: 'qwen-plus',
    fastModel: 'qwen-flash',
    apiKeyEnv: ['QWEN_API_KEY', 'TRPG_QWEN_API_KEY', 'DASHSCOPE_API_KEY', 'BAILIAN_API_KEY'],
    modelEnv: ['TRPG_QWEN_MODEL'],
    standardModelEnv: ['TRPG_QWEN_STANDARD_MODEL'],
    fastModelEnv: ['TRPG_QWEN_FAST_MODEL'],
    baseUrlEnv: ['TRPG_QWEN_BASE_URL'],
    supportsJson: true,
    supportsStreaming: true,
    supportsFileUpload: false,
    timeoutMs: { fast: 180000, standard: 180000 },
  },
  {
    id: 'custom-openai-compatible',
    label: 'Custom',
    provider: 'openai-compatible',
    baseUrl: null,
    standardModel: null,
    fastModel: null,
    apiKeyEnv: ['CUSTOM_LLM_API_KEY', 'LLM_API_KEY'],
    modelEnv: ['CUSTOM_LLM_MODEL', 'LLM_MODEL'],
    standardModelEnv: ['CUSTOM_LLM_STANDARD_MODEL'],
    fastModelEnv: ['CUSTOM_LLM_FAST_MODEL'],
    baseUrlEnv: ['CUSTOM_LLM_BASE_URL', 'LLM_BASE_URL'],
    supportsJson: true,
    supportsStreaming: true,
    supportsFileUpload: false,
    timeoutMs: { fast: 180000, standard: 180000 },
  },
];

export function getModelProfile(profileId = 'chatgpt') {
  return MODEL_PROFILES.find((profile) => profile.id === profileId) ?? MODEL_PROFILES[0];
}
